# Generated by Django 2.0.10 on 2019-01-28 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('unouno', models.BooleanField(default=True)),
                ('unodos', models.BooleanField(default=True)),
                ('unotres', models.BooleanField(default=True)),
                ('unocuatro', models.BooleanField(default=True)),
                ('unocinco', models.BooleanField(default=True)),
                ('unoseis', models.BooleanField(default=True)),
                ('unosiete', models.BooleanField(default=True)),
                ('unoocho', models.BooleanField(default=True)),
                ('unonueve', models.BooleanField(default=True)),
                ('unodiez', models.BooleanField(default=True)),
                ('unoonce', models.BooleanField(default=True)),
                ('unodoce', models.BooleanField(default=True)),
                ('unotrece', models.BooleanField(default=True)),
                ('unocatorce', models.BooleanField(default=True)),
                ('unoquince', models.BooleanField(default=True)),
                ('unodieciseis', models.BooleanField(default=True)),
                ('unodiecisiete', models.BooleanField(default=True)),
                ('unodieciocho', models.BooleanField(default=True)),
                ('unodiecinueve', models.BooleanField(default=True)),
                ('unoveinte', models.BooleanField(default=True)),
                ('unoveintiuno', models.BooleanField(default=True)),
                ('dosuno', models.BooleanField(default=True)),
                ('dosdos', models.BooleanField(default=True)),
                ('dostres', models.BooleanField(default=True)),
                ('tres', models.BooleanField(default=True)),
                ('tresuno', models.BooleanField(default=True)),
                ('tresdos', models.BooleanField(default=True)),
                ('trestres', models.BooleanField(default=True)),
                ('trescuatro', models.BooleanField(default=True)),
                ('trescinco', models.BooleanField(default=True)),
                ('tresseis', models.BooleanField(default=True)),
                ('cuatro', models.BooleanField(default=True)),
                ('cinco', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('unouno', models.BooleanField(default=True)),
                ('unodos', models.BooleanField(default=True)),
                ('unotres', models.BooleanField(default=True)),
                ('unocuatro', models.BooleanField(default=True)),
                ('unocinco', models.BooleanField(default=True)),
                ('unoseis', models.BooleanField(default=True)),
                ('unosiete', models.BooleanField(default=True)),
                ('unoocho', models.BooleanField(default=True)),
                ('unonueve', models.BooleanField(default=True)),
                ('unodiez', models.BooleanField(default=True)),
                ('unoonce', models.BooleanField(default=True)),
                ('unodoce', models.BooleanField(default=True)),
                ('unotrece', models.BooleanField(default=True)),
                ('unocatorce', models.BooleanField(default=True)),
                ('unoquince', models.BooleanField(default=True)),
                ('unodieciseis', models.BooleanField(default=True)),
                ('unodiecisiete', models.BooleanField(default=True)),
                ('unodieciocho', models.BooleanField(default=True)),
                ('unodiecinueve', models.BooleanField(default=True)),
                ('unoveinte', models.BooleanField(default=True)),
                ('unoveintiuno', models.BooleanField(default=True)),
                ('dosuno', models.BooleanField(default=True)),
                ('dosdos', models.BooleanField(default=True)),
                ('dostres', models.BooleanField(default=True)),
                ('tres', models.BooleanField(default=True)),
                ('tresuno', models.BooleanField(default=True)),
                ('tresdos', models.BooleanField(default=True)),
                ('trestres', models.BooleanField(default=True)),
                ('trescuatro', models.BooleanField(default=True)),
                ('trescinco', models.BooleanField(default=True)),
                ('tresseis', models.BooleanField(default=True)),
                ('cuatro', models.BooleanField(default=True)),
                ('cinco', models.BooleanField(default=True)),
                ('tipo', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(blank=True, max_length=30, null=True)),
                ('pregunta', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=70)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Proveedor')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='pregunta',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='comuna', chained_model_field='comuna', null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Realiza'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Proveedor'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Respuesta'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Rol'),
        ),
    ]
