# Generated by Django 2.0.10 on 2019-03-04 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('unouno', models.BooleanField(default=True)),
                ('unodos', models.BooleanField(default=True)),
                ('unotres', models.BooleanField(default=True)),
                ('unocuatro', models.BooleanField(default=True)),
                ('unocinco', models.BooleanField(default=True)),
                ('unoseis', models.BooleanField(default=True)),
                ('unosiete', models.BooleanField(default=True)),
                ('unoocho', models.BooleanField(default=True)),
                ('unonueve', models.BooleanField(default=True)),
                ('unodiez', models.BooleanField(default=True)),
                ('unoonce', models.BooleanField(default=True)),
                ('unodoce', models.BooleanField(default=True)),
                ('unotrece', models.BooleanField(default=True)),
                ('unocatorce', models.BooleanField(default=True)),
                ('unoquince', models.BooleanField(default=True)),
                ('unodieciseis', models.BooleanField(default=True)),
                ('unodiecisiete', models.BooleanField(default=True)),
                ('unodieciocho', models.BooleanField(default=True)),
                ('unodiecinueve', models.BooleanField(default=True)),
                ('unoveinte', models.BooleanField(default=True)),
                ('unoveintiuno', models.BooleanField(default=True)),
                ('dosuno', models.BooleanField(default=True)),
                ('dosdos', models.BooleanField(default=True)),
                ('dostres', models.BooleanField(default=True)),
                ('tres', models.BooleanField(default=True)),
                ('tresuno', models.BooleanField(default=True)),
                ('tresdos', models.BooleanField(default=True)),
                ('trestres', models.BooleanField(default=True)),
                ('trescuatro', models.BooleanField(default=True)),
                ('trescinco', models.BooleanField(default=True)),
                ('tresseis', models.BooleanField(default=True)),
                ('cuatrouno', models.BooleanField(default=True)),
                ('cinco', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.CharField(blank=True, default='Sin Nombre', max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('eval_inicial', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_formulario', models.CharField(blank=True, choices=[('FINALIZADO', 'FINALIZADO'), ('EN PROCESO', 'EN PROCESO')], max_length=30, null=True)),
                ('eval_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Comuna')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='Preg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=400, null=True)),
                ('seguimiento', models.BooleanField(default=False)),
                ('respuesta', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('N/A', 'N/A'), ('OTRO', 'OTRO')], max_length=400, null=True)),
                ('comentario', models.CharField(default='Sin Comentarios', max_length=400, null=True)),
                ('comentario2', models.CharField(default='Sin Comentarios', max_length=400, null=True)),
                ('formulario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Formulario')),
            ],
            options={
                'verbose_name': 'Medidas de Control',
                'verbose_name_plural': 'Medidas de Control',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('unouno', models.BooleanField(default=True)),
                ('unodos', models.BooleanField(default=True)),
                ('unotres', models.BooleanField(default=True)),
                ('unocuatro', models.BooleanField(default=True)),
                ('unocinco', models.BooleanField(default=True)),
                ('unoseis', models.BooleanField(default=True)),
                ('unosiete', models.BooleanField(default=True)),
                ('unoocho', models.BooleanField(default=True)),
                ('unonueve', models.BooleanField(default=True)),
                ('unodiez', models.BooleanField(default=True)),
                ('unoonce', models.BooleanField(default=True)),
                ('unodoce', models.BooleanField(default=True)),
                ('unotrece', models.BooleanField(default=True)),
                ('unocatorce', models.BooleanField(default=True)),
                ('unoquince', models.BooleanField(default=True)),
                ('unodieciseis', models.BooleanField(default=True)),
                ('unodiecisiete', models.BooleanField(default=True)),
                ('unodieciocho', models.BooleanField(default=True)),
                ('unodiecinueve', models.BooleanField(default=True)),
                ('unoveinte', models.BooleanField(default=True)),
                ('unoveintiuno', models.BooleanField(default=True)),
                ('dosuno', models.BooleanField(default=True)),
                ('dosdos', models.BooleanField(default=True)),
                ('dostres', models.BooleanField(default=True)),
                ('tres', models.BooleanField(default=True)),
                ('tresuno', models.BooleanField(default=True)),
                ('tresdos', models.BooleanField(default=True)),
                ('trestres', models.BooleanField(default=True)),
                ('trescuatro', models.BooleanField(default=True)),
                ('trescinco', models.BooleanField(default=True)),
                ('tresseis', models.BooleanField(default=True)),
                ('cuatrouno', models.BooleanField(default=True)),
                ('cinco', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['rut'],
            },
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('pregunta', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Asociación',
                'verbose_name_plural': 'Asociación comuna-pregunta',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Proveedor')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Proveedor'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Rol'),
        ),
    ]
