# Generated by Django 2.0.10 on 2019-02-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, max_length=400, null=True)),
                ('pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='comentario',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Comuna'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='estado_formulario',
            field=models.CharField(choices=[('FINALIZADO', 'FINALIZADO'), ('EN PROCESO', 'EN PROCESO')], default='EN PROCESO', max_length=30),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Realiza'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Asociada'),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
