# Generated by Django 2.0.10 on 2019-01-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predio',
            options={'verbose_name': 'Predio', 'verbose_name_plural': 'Predios'},
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='imagen',
        ),
    ]
