# Generated by Django 2.0.10 on 2019-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preg',
            name='respuesta',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
