# Generated by Django 2.0.10 on 2019-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0002_auto_20190116_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
