# Generated by Django 2.0.10 on 2019-03-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0002_auto_20190304_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preg',
            name='respuesta',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('N/A', 'N/A'), ('OTRO', 'OTRO')], max_length=400, null=True),
        ),
    ]
