# Generated by Django 2.0.10 on 2019-02-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0002_auto_20190212_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='estado_formulario',
            field=models.CharField(choices=[('FINALIZADO', 'FINALIZADO'), ('EN PROCESO', 'EN PROCESO')], max_length=30),
        ),
    ]
