# Generated by Django 2.0.10 on 2019-01-28 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0002_formulario_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='pregunta',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Realiza'),
        ),
    ]
