# Generated by Django 2.0.10 on 2019-03-04 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0003_auto_20190304_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=400, null=True)),
                ('seguimiento', models.BooleanField(default=False)),
                ('respuesta', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO'), ('N/A', 'N/A'), ('OTRO', 'OTRO')], max_length=400, null=True)),
                ('comentario', models.CharField(default='Sin Comentarios', max_length=400, null=True)),
                ('comentario2', models.CharField(default='Sin Comentarios', max_length=400, null=True)),
                ('formulario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Formulario')),
            ],
            options={
                'verbose_name': 'Medidas de Control',
                'verbose_name_plural': 'Medidas de Control',
            },
        ),
        migrations.RemoveField(
            model_name='preg',
            name='formulario_id',
        ),
        migrations.DeleteModel(
            name='Preg',
        ),
    ]
