# Generated by Django 2.0.10 on 2019-02-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0003_auto_20190212_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='respuesta',
        ),
    ]
