# Generated by Django 2.0.10 on 2019-01-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0003_auto_20190128_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParaPreguntar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Realiza')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Pregunta')),
            ],
        ),
    ]
