# Generated by Django 2.0.10 on 2019-01-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0003_formulario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Pregunta'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Respuesta'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
