# Generated by Django 2.0.10 on 2019-01-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0004_auto_20190116_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Comuna'),
        ),
    ]
