# Generated by Django 2.0.10 on 2019-01-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0004_parapreguntar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parapreguntar',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='parapreguntar',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='ParaPreguntar',
        ),
    ]
