# Generated by Django 2.0.10 on 2019-02-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0005_auto_20190128_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaBinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10)),
                ('comentario', models.CharField(max_length=300)),
                ('tipo', models.CharField(blank=True, default='BINARIA', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Respuesta_Binaria',
                'verbose_name_plural': 'Respuestas_Binarias',
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='pregunta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Comuna'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.RespuestaBinaria'),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
