# Generated by Django 2.0.10 on 2019-01-17 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0005_pregunta_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Comuna')),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='realiza',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Pregunta'),
        ),
    ]
