# Generated by Django 2.0.10 on 2019-01-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0005_auto_20190128_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Comuna'),
        ),
    ]
