# Generated by Django 2.0.10 on 2019-02-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0006_auto_20190205_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='respuesta',
        ),
    ]
