# Generated by Django 2.0.10 on 2019-01-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0006_auto_20190117_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=70)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Proveedor')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.RemoveField(
            model_name='predio',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='predio',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Predio',
        ),
    ]
