# Generated by Django 2.0.10 on 2019-01-29 15:24

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0006_auto_20190129_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='pregunta',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='comuna', chained_model_field='comuna', null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Realiza'),
        ),
    ]
