# Generated by Django 2.0.10 on 2019-01-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0007_formulario_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Realiza'),
        ),
    ]
