# Generated by Django 2.0.10 on 2019-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0008_formulario_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='pregunta1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='respuesta1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
