# Generated by Django 2.0.10 on 2019-02-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0009_auto_20190205_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='pregunta1',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='respuesta1',
        ),
    ]
