# Generated by Django 2.0.10 on 2019-01-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0009_auto_20190129_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Pregunta'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
