# Generated by Django 2.0.10 on 2019-01-17 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formularioscdc', '0009_auto_20190117_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulari',
            new_name='Formulario',
        ),
    ]
