# Generated by Django 2.0.10 on 2019-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0010_auto_20190205_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='formulario',
            name='pregunta',
            field=models.ManyToManyField(blank=True, null=True, to='formularioscdc.Realiza'),
        ),
    ]
