# Generated by Django 2.0.10 on 2019-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0010_auto_20190117_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
