# Generated by Django 2.0.10 on 2019-01-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0011_pregunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Pregunta'),
        ),
    ]
