# Generated by Django 2.0.10 on 2019-02-08 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioscdc', '0011_auto_20190208_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='pregunta',
            field=models.ManyToManyField(blank=True, limit_choices_to={'comuna': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioscdc.Comuna')}, to='formularioscdc.Realiza'),
        ),
    ]
